# Generated by Django 5.1.1 on 2024-11-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
